# -*- coding: utf-8 -*-
"""Week4_Day6_Ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7aSNskbtSyCLcCDh6uIufLn0YjfDxQ2

Apolo Barnabas
Week4_Day6
"""

import pandas as pd
from sklearn.datasets import load_iris

# Step 1
# Load the Iris dataset

iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target_names[iris.target]

#Step 2: Check the Number of Rows Before Removing Duplicates
duplicate_rows = df.duplicated()

print("Number of duplicate rows:", duplicate_rows.sum())

#Step 3 Identify Duplicate Rows
duplicate_rows = df.duplicated()

print("Number of duplicate rows:", duplicate_rows.sum())
print(df[duplicate_rows])

# Step 4: Remove Duplicate Rows
df_cleaned = df.drop_duplicates()

# Step 5: Verify Duplicate Removal
rows_before = len(df)
rows_after = len(df_cleaned)

print("Number of rows after removing duplicates:", rows_after)
print("Number of rows removed:", rows_before - rows_after)

# Step 6 Confirm No Duplicates Remain
print("Remaining duplicate rows:", df_cleaned.duplicated().sum())

#Q2
# Check for missing values in each column
missing_values = df.isnull().sum()

# Display only columns with missing values
print(missing_values[missing_values > 0])

#
df_drop = df.dropna() # Removed subset=['Embarked'] as it's not a column in the Iris dataset

print("Rows before:", len(df))
print("Rows after:", len(df_drop))

import pandas as pd
print(df.isnull().sum())

print(df.head())

import pandas as pd

df = pd.read_csv("Iris.csv")

from google.colab import data_table
# Create FamilySize feature
df['FamilySize'] = df['SepalLengthCm'] + df['PetalWidthCm'] + 1

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create a new feature for Iris dataset (e.g., combining sepal and petal measurements)
df['sepal_petal_sum'] = df['sepal length (cm)'] + df['petal width (cm)'] + 1

# Display first few rows
print(df.head())

# Check data types
print("\nData Types:")
print(df.dtypes)

#Q4 Visualization

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# The columns are selected
num_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in num_cols:
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    sns.histplot(df[col], kde=True, ax=axes[0])
    axes[0].set_title(f'Histogram - {col}')

    sns.boxplot(x=df[col], ax=axes[1])
    axes[1].set_title(f'Boxplot - {col}')

    plt.show()

# Detect Outliers Using IQR

def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[(data[column] < lower) | (data[column] > upper)]
    return outliers
sepal_length_outliers = detect_outliers_iqr(df, 'sepal length (cm)')
print(f"Number of 'sepal length (cm)' outliers: {len(sepal_length_outliers)}")

#Detect Outliers Using Z-Score

from scipy.stats import zscore
import numpy as np

z_scores = np.abs(zscore(df[num_cols], nan_policy='omit'))

outlier_rows = (z_scores > 3).any(axis=1)

print("Number of rows with outliers:", outlier_rows.sum())

#Handle Outliers
df_capped = df.copy()

for col in num_cols:
    upper_cap = df_capped[col].quantile(0.98)
    lower_cap = df_capped[col].quantile(0.02)

    df_capped[col] = df_capped[col].clip(
        lower=lower_cap,
        upper=upper_cap
    )

#A
for col in num_cols:
    print(col)
    print(df[col].quantile([0.95, 0.98, 0.99]))
    print()

#B. Log Transformation
import numpy as np

df_log = df.copy()

df_log['petal width (cm)'] = np.log1p(df_log['petal width (cm)'])
# Vizualisation
plt.title('Fare After Log Transformation')
plt.show()

#C. Remove Outlier Rows
# We will use 'petal width (cm)' as an example numerical column.
column_to_process = 'petal width (cm)'

Q1 = df[column_to_process].quantile(0.25)
Q3 = df[column_to_process].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df_removed = df[
    (df[column_to_process] >= lower) &
    (df[column_to_process] <= upper)
]

print("Original shape:", df.shape)
print("After removal:", df_removed.shape)

#Compare Before and After Treatment

fig, axes = plt.subplots(1, 2, figsize=(12, 4))

column_to_visualize = 'petal width (cm)'

sns.boxplot(x=df[column_to_visualize], ax=axes[0])
axes[0].set_title('Before Treatment')

sns.boxplot(x=df_capped[column_to_visualize], ax=axes[1])
axes[1].set_title('After Quantile Capping')

plt.show()

#Comparison
comparison = pd.DataFrame({
    'Before': df['petal width (cm)'].describe(),
    'After_Capping': df_capped['petal width (cm)'].describe()
})

print(comparison)

#Q5
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd

# Normally distributed features (using Iris dataset columns)
standard_features = ['sepal length (cm)', 'sepal width (cm)']

# Skewed or bounded features (using Iris dataset columns)
minmax_features = ['petal length (cm)', 'petal width (cm)']

import matplotlib.pyplot as plt

df[standard_features + minmax_features].hist(figsize=(10, 5))
plt.show()

standard_scaler = StandardScaler()

df_scaled = df.copy()

df_scaled[standard_features] = standard_scaler.fit_transform(
    df_scaled[standard_features]
)

print(df_scaled[standard_features].describe())
print(df_scaled[minmax_features].describe())

from sklearn.preprocessing import StandardScaler, MinMaxScaler

df_scaled = df.copy()

# Standard Scaling
standard_features = ['sepal length (cm)', 'sepal width (cm)']
standard_scaler = StandardScaler()
df_scaled[standard_features] = standard_scaler.fit_transform(
df_scaled[standard_features]
)

# Min-Max Scaling
minmax_features = ['petal length (cm)', 'petal width (cm)']
minmax_scaler = MinMaxScaler()
df_scaled[minmax_features] = minmax_scaler.fit_transform(
    df_scaled[minmax_features]
)

print(df_scaled.head())

#Q6
# Check categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("Categorical columns:")
print(categorical_cols)

from sklearn.preprocessing import OneHotEncoder

# The nominal_cols were previously for the Titanic dataset.
nominal_cols = ['species']

# Create encoded columns
encoded_df = pd.get_dummies(
    df[nominal_cols],
    drop_first=True,  # avoids multicollinearity
    dtype=int
)

print(encoded_df.head())

#Apply Label Encoding (Ordinal Variables)
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Drop original categorical columns
df_encoded = df.drop(columns=nominal_cols)

# Add encoded features
df_encoded = pd.concat(
    [df_encoded, encoded_df],
    axis=1
)

print(df_encoded.head())

print(df_encoded.info())

print(
    df_encoded.select_dtypes(include=['object']).columns
)

#Q7..
import pandas as pd

# Define age bins and labels
age_bins = [0, 12, 18, 60, 100]
age_labels = ['Child', 'Teen', 'Adult', 'Senior']